dist: trusty

language: go

go:
  - 1.9.x

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/vendor

services:
  - docker

install:
  - curl https://glide.sh/get | sh

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

script:
  - make test

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    make TAG=${TRAVIS_TAG} deploy;
    fi
  - make TAG=latest deploy
  - make TAG=${TRAVIS_COMMIT} deploy
  - bash <(curl -s https://codecov.io/bash)
